### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by RishabGuggali** [Blasanka/aws_s3_plugin#11]
D/UploadTask(32647): Failed to upload: 6 due to Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 1AC7FB214CD42697)
E/Transfer(32647): onError: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 1AC7FB214CD42697), S3 Extended Request ID: SXy5z7M9fETAsSSc6GaZsABusvghoixl4Dk8bjI5uJ02xxb4ZVP26WqpCkEI8Ji7cmMyuwXfh68=
D/Transfer(32647): ID:6 bytesCurrent: 157363 bytesTotal: 157363 100%

please help me to solve this

**Comment by leoshak** [comment]
Hi @RishabGuggali, reason can be:

This error indicates that the application tried to perform an Amazon Simple Storage Service (Amazon S3) operation that failed because of a problem with one of the following:

- Credentials or role specified in your application code
- Policy attached to the Amazon Elastic Compute Cloud (Amazon EC2) instance profile role
- Amazon S3 VPC endpoint policy
- Amazon S3 source and destination bucket policies

Read more [here](https://aws.amazon.com/premiumsupport/knowledge-center/emr-s3-403-access-denied/).

**Comment by 247software-vaibhav-joshi** [comment]
> D/UploadTask(32647): Failed to upload: 6 due to Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 1AC7FB214CD42697)
> E/Transfer(32647): onError: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 1AC7FB214CD42697), S3 Extended Request ID: SXy5z7M9fETAsSSc6GaZsABusvghoixl4Dk8bjI5uJ02xxb4ZVP26WqpCkEI8Ji7cmMyuwXfh68=
> D/Transfer(32647): ID:6 bytesCurrent: 157363 bytesTotal: 157363 100%
> 
> please help me to solve this

Any Luck?
